/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphsimulator;

/**
 *
 * @author Asus
 */
public class UI extends javax.swing.JPanel {

    /**
     * Creates new form UI
     */
    public UI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        directionGroup = new javax.swing.ButtonGroup();
        weightGroup = new javax.swing.ButtonGroup();
        panelHome = new javax.swing.JPanel();
        labelChooseGraph = new javax.swing.JLabel();
        radioButtonDirected = new javax.swing.JRadioButton();
        radioButtonWeighted = new javax.swing.JRadioButton();
        radioButtonUndirected = new javax.swing.JRadioButton();
        radioButtonUnweighted = new javax.swing.JRadioButton();
        buttonNext = new javax.swing.JButton();
        labelError = new javax.swing.JLabel();

        panelHome.setBackground(new java.awt.Color(0, 44, 73));

        labelChooseGraph.setFont(new java.awt.Font("Eras Medium ITC", 0, 48)); // NOI18N
        labelChooseGraph.setForeground(new java.awt.Color(102, 102, 255));
        labelChooseGraph.setText("CHOOSE GRAPH");

        radioButtonDirected.setBackground(new java.awt.Color(0, 44, 73));
        directionGroup.add(radioButtonDirected);
        radioButtonDirected.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        radioButtonDirected.setText("Directed");
        radioButtonDirected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonDirectedActionPerformed(evt);
            }
        });

        radioButtonWeighted.setBackground(new java.awt.Color(0, 44, 73));
        weightGroup.add(radioButtonWeighted);
        radioButtonWeighted.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        radioButtonWeighted.setText("Weighted");
        radioButtonWeighted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonWeightedActionPerformed(evt);
            }
        });

        radioButtonUndirected.setBackground(new java.awt.Color(0, 44, 73));
        directionGroup.add(radioButtonUndirected);
        radioButtonUndirected.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        radioButtonUndirected.setText("Undirected");
        radioButtonUndirected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonUndirectedActionPerformed(evt);
            }
        });

        radioButtonUnweighted.setBackground(new java.awt.Color(0, 44, 73));
        weightGroup.add(radioButtonUnweighted);
        radioButtonUnweighted.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        radioButtonUnweighted.setText("Unweighted");
        radioButtonUnweighted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonUnweightedActionPerformed(evt);
            }
        });

        buttonNext.setBackground(new java.awt.Color(0, 44, 73));
        buttonNext.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        buttonNext.setForeground(new java.awt.Color(51, 51, 51));
        buttonNext.setText("Next");
        buttonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNextActionPerformed(evt);
            }
        });

        labelError.setFont(new java.awt.Font("Ebrima", 2, 20)); // NOI18N
        labelError.setForeground(new java.awt.Color(255, 33, 33));
        labelError.setText("Error : Select Direction!");

        javax.swing.GroupLayout panelHomeLayout = new javax.swing.GroupLayout(panelHome);
        panelHome.setLayout(panelHomeLayout);
        panelHomeLayout.setHorizontalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addContainerGap(269, Short.MAX_VALUE)
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioButtonDirected, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioButtonUndirected, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(196, 196, 196)
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioButtonWeighted, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioButtonUnweighted, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(207, 207, 207))
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHomeLayout.createSequentialGroup()
                        .addGap(396, 396, 396)
                        .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(buttonNext, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelChooseGraph, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelHomeLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(labelError, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelHomeLayout.setVerticalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(labelChooseGraph, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioButtonDirected, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioButtonWeighted, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioButtonUndirected, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioButtonUnweighted, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84)
                .addComponent(buttonNext, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(labelError, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void radioButtonDirectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonDirectedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButtonDirectedActionPerformed

    private void radioButtonWeightedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonWeightedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButtonWeightedActionPerformed

    private void radioButtonUndirectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonUndirectedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButtonUndirectedActionPerformed

    private void radioButtonUnweightedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonUnweightedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButtonUnweightedActionPerformed

    private void buttonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonNextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonNext;
    private javax.swing.ButtonGroup directionGroup;
    private javax.swing.JLabel labelChooseGraph;
    private javax.swing.JLabel labelError;
    private javax.swing.JPanel panelHome;
    private javax.swing.JRadioButton radioButtonDirected;
    private javax.swing.JRadioButton radioButtonUndirected;
    private javax.swing.JRadioButton radioButtonUnweighted;
    private javax.swing.JRadioButton radioButtonWeighted;
    private javax.swing.ButtonGroup weightGroup;
    // End of variables declaration//GEN-END:variables
}
