/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphsimulator;

/**
 *
 * @author Asus
 */
public class UI1 extends javax.swing.JPanel {

    /**
     * Creates new form UI1
     */
    public UI1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGrouopInput = new javax.swing.ButtonGroup();
        labelGraphInputStyle = new javax.swing.JLabel();
        radionButtonDrawGraph = new javax.swing.JRadioButton();
        radioButtonNumericalInput = new javax.swing.JRadioButton();
        labelError = new javax.swing.JLabel();
        buttonNext = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 44, 73));
        setPreferredSize(new java.awt.Dimension(1168, 874));

        labelGraphInputStyle.setFont(new java.awt.Font("Eras Medium ITC", 0, 48)); // NOI18N
        labelGraphInputStyle.setForeground(new java.awt.Color(102, 102, 255));
        labelGraphInputStyle.setText("GRAPH INPUT STYLE");
        labelGraphInputStyle.setMaximumSize(new java.awt.Dimension(362, 55));
        labelGraphInputStyle.setMinimumSize(new java.awt.Dimension(362, 55));

        radionButtonDrawGraph.setBackground(new java.awt.Color(0, 44, 73));
        buttonGrouopInput.add(radionButtonDrawGraph);
        radionButtonDrawGraph.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        radionButtonDrawGraph.setText("Draw Graph");
        radionButtonDrawGraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radionButtonDrawGraphActionPerformed(evt);
            }
        });

        radioButtonNumericalInput.setBackground(new java.awt.Color(0, 44, 73));
        buttonGrouopInput.add(radioButtonNumericalInput);
        radioButtonNumericalInput.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        radioButtonNumericalInput.setText("Numerical Input");
        radioButtonNumericalInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonNumericalInputActionPerformed(evt);
            }
        });

        labelError.setFont(new java.awt.Font("Ebrima", 2, 20)); // NOI18N
        labelError.setForeground(new java.awt.Color(255, 33, 33));
        labelError.setText("Error : Select One");

        buttonNext.setBackground(new java.awt.Color(0, 44, 73));
        buttonNext.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        buttonNext.setForeground(new java.awt.Color(51, 51, 51));
        buttonNext.setText("Next");
        buttonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(379, 379, 379)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(buttonNext, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelGraphInputStyle, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE))
                .addGap(332, 332, 332))
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelError, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(413, 413, 413))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(radioButtonNumericalInput, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(radionButtonDrawGraph, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addComponent(labelGraphInputStyle, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radionButtonDrawGraph, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioButtonNumericalInput, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122)
                .addComponent(buttonNext, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                .addComponent(labelError)
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void radioButtonNumericalInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonNumericalInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButtonNumericalInputActionPerformed

    private void radionButtonDrawGraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radionButtonDrawGraphActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radionButtonDrawGraphActionPerformed

    private void buttonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonNextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGrouopInput;
    private javax.swing.JButton buttonNext;
    private javax.swing.JLabel labelError;
    private javax.swing.JLabel labelGraphInputStyle;
    private javax.swing.JRadioButton radioButtonNumericalInput;
    private javax.swing.JRadioButton radionButtonDrawGraph;
    // End of variables declaration//GEN-END:variables
}
